feat: add ignoredQueryElementAll options
dixons/codeceptjs-resemblehelper pull request #15
Opened 2021-02-19 17:57 UTC by patrjam

2021-02-22 12:02 UTC, Trawais submitted a review, later dismissed

2021-02-22 13:58 UTC, CDJojn requested changes

2021-02-22 13:58 UTC, CDJojn commented on README.md
> +Functionality element selection is similar as `querySelectorAll` in `DOM`, `ignoredQueryElementAll` will find all same elements on the page and ignore them.
i would use word "identical" rather than "same"

2021-02-22 13:58 UTC, CDJojn commented on README.md
> +Functionality element selection is similar as `querySelectorAll` in `DOM`, `ignoredQueryElementAll` will find all same elements on the page and ignore them.
or "query suitable"

2021-02-22 15:30 UTC, Trawais approved these changes

2021-02-23 08:14 UTC, CDJojn approved these changes

2021-02-23 08:20 UTC, merged