feat: add playwright support for ignored options
dixons/codeceptjs-resemblehelper pull request #18
Opened 2021-03-15 10:49 UTC by patrjam

2021-03-15 11:02 UTC, Stanin84 submitted a review, later dismissed

2021-03-15 13:23 UTC, Trawais requested changes

2021-03-15 13:23 UTC, Trawais commented on index.js
> +    let helper = this._getHelper();
const

2021-03-16 07:38 UTC, Stanin84 approved these changes

2021-03-16 09:15 UTC, Trawais approved these changes

2021-03-16 12:58 UTC, merged