add example tests for prepareBaseImage
dixons/codeceptjs-resemblehelper pull request #2
Opened 2021-01-13 16:36 UTC by patrjam

2021-01-14 08:26 UTC, CDJojn requested changes

2021-01-14 08:26 UTC, CDJojn commented on package.json
> +    "codeceptjs-chai": "^2.2.0",
Eh.... codeceptjs-assert please

2021-01-14 08:26 UTC, CDJojn commented on steps_file.js
> +module.exports = function() {
is this file necessary here?

2021-01-14 08:26 UTC, CDJojn commented on tests/prepareBaseImage-false_test.js
> +Scenario(
what about to have all these RXX test order from 1-18? :D

2021-01-14 08:26 UTC, CDJojn commented on tools/debugCatcher.js
> +    const orig = Helper.prototype.debug;
why are working with prototype? this is not recommended - debug function is normally accessible by this.debug()

2021-01-14 08:26 UTC, CDJojn commented on tests/prepareBaseImage-false_test.js
> +    const debugCatcher = new DebugCatcher();
Why are you using helper as standard class? Why is helper not instanced in config file by standard way?

2021-01-14 13:02 UTC, CDJojn requested changes

2021-01-14 13:02 UTC, CDJojn commented on tests/prepareBaseImage-false_test.js
> +    const debugCatcher = new DebugCatcher();
Discussed - this is ok this way.

2021-01-14 13:02 UTC, CDJojn commented on tools/debugCatcher.js
> +    const orig = Helper.prototype.debug;
Discussed - this is OK.

2021-01-14 13:02 UTC, CDJojn commented on tests/prepareBaseImage-false_test.js
> +Scenario(
Discussed - this order is ok - it is based on base image creating.

2021-01-14 14:01 UTC, CDJojn approved these changes

2021-01-19 08:40 UTC, Trawais commented on package.json
> +    "codeceptjs-chai": "^2.2.0",
replaced

2021-01-19 08:49 UTC, Trawais commented on steps_file.js
> +// in this file you can append custom step methods to 'I' object
I believe we don't need this file anymore.

2021-01-19 08:50 UTC, Trawais approved these changes

2021-01-19 09:31 UTC, merged