feat: add flag createSubFoldersInBaseFolder
dixons/codeceptjs-resemblehelper pull request #31
Opened 2021-07-27 17:22 UTC by patrjam

2021-07-28 07:49 UTC, CDJojn approved these changes

2021-07-28 10:00 UTC, Trawais requested changes

2021-07-28 12:42 UTC, patrjam commented on README.md
> +`createSubFoldersInBaseFolder`: Optional. When `true` is set, for every base image is created sub folder in base image. Sub folder is named as first 50 chars of test `Scenario` title.
Yes thanks, my mistake. It's something like a "typo" 😃

2021-07-28 13:13 UTC, patrjam commented on README.md
> +```js
With `js` format it looks much better in documentation ;)

2021-07-29 07:36 UTC, Trawais approved these changes

2021-07-29 07:40 UTC, CDJojn approved these changes

2021-07-29 07:49 UTC, merged