perf(rename): change package name for release process
dixons/codeceptjs-resemblehelper pull request #9
Opened 2021-02-02 16:45 UTC by patrjam

BREAKING CHANGE: forked repository changed package name.

2021-02-02 16:52 UTC, Stanin84 approved these changes

2021-02-03 08:12 UTC, CDJojn approved these changes

2021-02-03 12:33 UTC, Trawais requested changes

2021-02-03 12:33 UTC, Trawais commented on .gitignore
> +.git
This looks very suspicious to me. Please remove it from the `.gitignore`

2021-02-03 12:33 UTC, Trawais commented on .gitignore
> +.git
This could spoil the whole repository. I would definitely NOT do this.

2021-02-03 12:33 UTC, Trawais commented on .npmignore
> +.gitignore
I would ignore `.git` folder here

2021-02-03 14:11 UTC, Trawais approved these changes

2021-02-03 14:14 UTC, CDJojn approved these changes

2021-02-03 14:26 UTC, merged